export const exercisesMapping = {
  upright_rows: "Upright Rows",
  lateral_raises_machine: "Lateral Raises Machine",
  reverse_flys: "Reverse Flys",
  front_raises_rod: "Front Raises Rod",
  overhead_press_rod: "Overhead Press Rod",
  front_raises_hammer: "Front Raises - Hammer Style",
  lateral_raises: "Lateral Raises",
  shrugs: "Shrugs",
  lat_dumbbell_row: "Lat Dumbbell Row",
  t_bar: "T Bar",
  vbar_pulldown: "V Bar Pulldown",
  lat_pulldown_front: "Lat Pulldown Front",
  lat_pulldown_back: "Lat Pulldown Back",
  seaterd_rows: "Seated Rows",
  incline_bench_dumbbell: "Incline Bench Dumbbell",
  decline_bench_dumbbell: "Decline Bench Dumbbell",
  flat_bench_dumbbell: "Flat Bench Dumbbell",
  incline_bench_barbell: "Incline Bench Barbell",
  decline_bench_barbell: "Decline Bench Barbell",
  flat_bench_barbell: "Flat Bench Barbell",
  flys: "Flys",
  chest_squeeze_press: "Chest Squeeze Press",
  "24_s": "24's",
  overhead_press: "Overhead Press",
  hammer_curls: "Hammer Curls",
  v_bar_pulldown: "V Bar Pulldown",
  rope_pulldown: "Rope pulldown",
  bicep_curls: "Bicep Curls",
  preacher_curls: "Preacher Curls",
  skull_crusher: "Skull Crusher",
  bicep_concentration_curls: "Bicep Concentration Curls",
  single_arm_overhead_extension: "Single Arm Overhead Extension",
  hindu_squats: "Hindu Squats",
  single_dumbbell_squats: "Single Dumbbell Squats",
  sumo_squats: "Sumo Squats",
  weighted_barbell_squats: "Weighted Barbell Squats",
  smith_machine_full_squats: "Smith Machine Full Squats",
  smith_machine_squat: "Smith Machine Squats",
  smith_machine_lunges: "Smith Machine Lunges",
  weighted_lunges: "Weighted Lunges",
  leg_press: "Leg Press",
  leg_extensions: "Leg Extensions",
  leg_curls: "Leg Curls",
  calf_raises: "Calf Raises",
  hanging_knee_raises: "Hanging Knee Raises",
  plank: "Plank",
  reverse_crunches: "Reverse Crunches",
  decline_bench_crunches: "Decline Bench Crunches",
  mountain_climbers: "Mountain Climbers",
  side_plank: "Side Plank",
  heel_taps: "Heel Taps",
  russian_twists: "Russian Twists",
  scissor_kicks: "Scissor Kicks",
};
